services:
  drone:
    container_name: drone
    image: "drone/drone:2.24"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./volumes/drone:/data"
      - "/etc/localtime:/etc/localtime:ro"
    restart: always
    ports:
      - 80:80
    env_file:
      - .env
  drone-agent:
    container_name: drone-runner
    image: drone/drone-runner-docker:1
    command: agent
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - drone
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "/etc/localtime:/etc/localtime:ro"
    env_file:
      - .env
